name: 'Generate build manifest'
description: 'Generates a build manifest JSON based on refs / package.json'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  scm-info:
    description: 'Get information from SCM/GitHub'
    required: false
    default: 'true'
  package-info:
    description: 'Get information from package.json'
    required: false
    default: 'true'
  action-info:
    description: 'Write GitHub action info in the manifest'
    required: false
    default: 'true'
  append-dockerfile:
    description: 'Automatically append COPY command in Dockerfile'
    required: false
    default: 'true'
  manifest-file:
    description: 'Manifest filename'
    required: false
    default: 'build-manifest.json'
  working-directory:
    description: 'Working directory, this is where the dockerfile should be and where the build-manifest will be written'
    required: false
    default: './'
outputs:
  manifest-content:
    description: 'The content of the generated manifest'
runs:
  using: 'node20'
  main: 'dist/index.js'